### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by dakeli** [prophesee-ai/prophesee-automotive-dataset-toolbox#10]

**Comment by laurentbristiel** [comment]
please provide more information about the problem you encountered. 
What dataset did you try to download? What error did you get?

**Comment by dakeli** [comment]
The owncloud download speed is very slow, and the torrent file has no nodes.

**Comment by dakeli** [comment]
The owncloud download speed is very slow, and the torrent file has no nodes.

**Comment by laurentbristiel** [comment]
Please try again to download the torrent file (Large_Automotive_Detection_Dataset.torrent) that can be found in the folder (link to the folder was shared when you signed-up for the Datasets). You might be using an old/obsolte torrent file, which would explain why it does not work on your side.
