### ISSUE TITLE
how to visualize ncar dataset

### ISSUE THREAD

**Issue by likui01** [prophesee-ai/prophesee-automotive-dataset-toolbox#11]
hi, I am trying to visualize the NCar dataset. The code provided is for the object detection dataset. If I read the .dat file, it loads an array.  how to reshape it into volume. 
Can you help in this regard?
@laurentbristiel  @dmigliore

**Comment by dEcmir** [comment]
what you have when you read the dat file is the actual sequence of events, which is the list of light changes detected by the sensor in chronological order. 

to visualize you can leverage the fonctions in the visualize folders of this repository , call `make_binary_histo` on the array you obtained for instance.

However if you are interested you'll find much more resources about event based some of it free and some of it open source [on our website ](https://docs.prophesee.ai/stable/index.html)
