### ISSUE TITLE
Torrent file for downloading datasets not working

### ISSUE THREAD

**Issue by 82magnolia** [prophesee-ai/prophesee-automotive-dataset-toolbox#13]
Hello, thanks for the nice datasets. I am trying to download the 1 Megapixel Automotive Detection Dataset and the GEN1 Automotive Detection Dataset. While both datasets have a torrent file provided, I was not able to download the files using the torrent files. I wonder if there are any issues with the torrent files. While directly downloading from the owncloud repository is an option, it takes too long (as noted from another issue).

**Comment by laurentbristiel** [comment]
Hello,
sorry for the delay to answer.
I tried the torrent file for the "1 Megapixel Automotive Detection Dataset" this morning and it worked OK (slow but working).
What problem did you face? What is unable to connect or very slow? Could you re-try?

**Comment by 82magnolia** [comment]
I am currently trying to download the dataset using qBittorrent on Ubuntu 18.04. Every time I initiate the download qBittorrent shows that the download is 'stalled' and that there are no seeds, as shown on the screenshot below. Would it be possible to know the torrent client that you have tested with? Perhaps changing the torrent client might work for me.

![image](https://user-images.githubusercontent.com/31164435/124403210-27e00300-dd70-11eb-991a-1dac6f9a28de.png)

**Comment by 82magnolia** [comment]
I have also tried with Transmission and it returns an error: Connection failed. I suspect this is also due to the fact that there are no seeds.

![image](https://user-images.githubusercontent.com/31164435/124405113-ac368400-dd78-11eb-8b6f-f414d9f5e03d.png)

**Comment by laurentbristiel** [comment]
We tried again on several laptop to download the ["GEN1 Automotive Detection Dataset"](https://www.prophesee.ai/2020/01/24/prophesee-gen1-automotive-detection-dataset/) and it works OK for us. 

Could you re-download the Torrent file on our server and try again?
(file "ATIS Automotive Detection Dataset.torrent")
(you might have an older version that could cause some problem)

**Comment by 82magnolia** [comment]
Hello, I have tried re-downloading the torrent file, but it still does not work. Perhaps the seed could not be detected from other continents (although I am not completely sure as I am not an expert in this area). Were the torrent files tested on laptops located in the same area?

**Comment by laurentbristiel** [comment]
We tried on several laptops in different cities, but all located in France. Though we regularly have people from all over the world that download the datasets via torrent and it works OK usually. You tried to download several datasets from us and none of them worked? If so, I would say there is a network/configuration/security issue on the way tha prevent you from downloading (maybe try from another place, like home instead of university or something like that..)

**Comment by 82magnolia** [comment]
I should definitely try that out. Thanks for the help!
