### ISSUE TITLE
Issue in data read

### ISSUE THREAD

**Issue by ahasssan** [prophesee-ai/prophesee-automotive-dataset-toolbox#15]
Hi, I was trying to display the data but it is giving me an error that the index is out of range. Can you please help me to address this? I am using google colab. 
![image](https://user-images.githubusercontent.com/88798996/129089660-520fb4db-a922-477f-bc5e-37bea632102b.png)

**Comment by laurentbristiel** [comment]
Hi,
do you have the corresponding box file in the folder where the .dat file is located?
This script plays simultaneously files and their boxes but all the files (.dat and .npy) should be in the same folder.

**Comment by eminguney** [comment]
Hi, I have the same problem and it didn't work. Can I learn how to fix this? 
I have a box file corresponding to a .dat file. They are all inside the content file but I keep getting the same error.

Thanks
