### ISSUE TITLE
Error while loading a dat file

### ISSUE THREAD

**Issue by ahasssan** [prophesee-ai/prophesee-automotive-dataset-toolbox#16]
Hi, I was trying to visualize a .dat file from Prophesee_dataset_car_n and your visualization file is giving me an error like this.
![image](https://user-images.githubusercontent.com/88798996/134303479-bafc0b99-41c7-498c-918f-efdbc14914f7.png)
Can you please help me to figure it out? Thanks

**Comment by laurentbristiel** [comment]
Hello @ahasssan 
could you share the content of your "content" folder where the .dat file you are trying to vizualize is? (you need to have the .npy files in there as well for the vizualisation to work).
