### ISSUE TITLE
1 Megapixel Automotive Detection Dataset 

### ISSUE THREAD

**Issue by wds320** [prophesee-ai/prophesee-automotive-dataset-toolbox#17]
Hello, thanks for your sharing.  I have some questions about 1 Megapixel Automotive Detection Dataset. Could you help me on that?

**1.** When I used your dataset visualization toolbox, I found that some labels are not aligned and some events are just like mosaic. Here are some examples and I am confused of that. I wonder whether you have cleaned the data in certain way before training?

![图片1](https://user-images.githubusercontent.com/72446915/147375902-09cadf62-ca00-44f8-9395-bc8335ea3293.png)

**2.** Since the 1 Megapixel Automotive Detection Dataset only provides event data without rgb, I cannot distinguish day/night data. I wonder whether there is a way that I can pick out the event data recorded in the night.

Thanks a lot!

**Comment by wds320** [comment]
Hi, 

Thanks a lot for your detailed explanation. I still want to confirm one small thing about the dataset.
&nbsp;For "mosaic"data, I'm sure it comes from the Gen4 recording(1280x720 resolution). And some labels are not aligned when I visualize the dataset. So should we clean the dataset before training?


Thanks again!


Best Regards!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prophesee-ai/prophesee-automotive-dataset-toolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [prophesee-ai/prophesee-automotive-dataset-toolbox] 1 Megapixel Automotive Detection Dataset  (Issue #17)





 
Hi, regarding your questions:
  
It's possible that some noise is introduced from the manual labeling or camera synchronization process, depending on the type of dataset.  The "mosaic" feature that you have observed comes probably from our Gen1 recording, where the data resolution is limited and the flickering in the tunnel triggers some noise.
 
the data delivered are not distinguished by day&amp;night scenes. However, you might notice some flickering effect at night triggered by the light.
  
You can find more information from the two paper referenced here.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wds320** [comment]
> Hi, regarding your questions:
> 
> 1. It's possible that some noise is introduced from the manual labeling or camera synchronization process, depending on the type of dataset.  The "mosaic" feature that you have observed comes probably from our Gen1 recording, where the data resolution is limited and the flickering in the tunnel triggers some noise.
> 2. the data delivered are not distinguished by day&night scenes. However, you might notice some flickering effect at night triggered by the light.
> 
> You can find more information from the two paper referenced [here](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox#evaluation-using-the-coco-api).



> 

Hi,
Thanks a lot for your detailed explanation. I still want to confirm one small thing about the dataset.
 For "mosaic"data, I'm sure it comes from the Gen4 recording(1280x720 resolution). And some labels are not aligned when I visualize the dataset. So should we clean the dataset before training?

Thanks again!

Best Regards!

**Comment by f-zhen** [comment]
Thank you for the conformation of the dataset. From the training point of view, it is always better to keep the dataset as clean as possible. But if this label noise only presents in a relatively small portion of the data, you may also want to train your detector without cleaning it. Of course, that all depends on your time budge and end purpose.
Best,

**Comment by wds320** [comment]
> Thank you for the conformation of the dataset. From the training point of view, it is always better to keep the dataset as clean as possible. But if this label noise only presents in a relatively small portion of the data, you may also want to train your detector without cleaning it. Of course, that all depends on your time budge and end purpose. Best,

OK, now I see! 
Thank you!
