### ISSUE TITLE
Availability of GPS data

### ISSUE THREAD

**Issue by Tobias-Fischer** [prophesee-ai/prophesee-automotive-dataset-toolbox#2]
Hi there,
I would be interested in the GPS data besides the annotation for cars/pedestrians. Is there any chance to access these data?

Many thanks,
Tobias

**Comment by dmigliore** [comment]
Hi Tobias,
in this version we do not have the GPS data. 
We just mounted the sensor and did the recording to test the capabilities of the event-based camera. 
Why you need the GPS? Are you planning to test localization? Do you need a egomotion reference?

**Comment by Tobias-Fischer** [comment]
Hi, no problem. Yes I would have liked to test localisation. Closing here for now - please let me know if you include GPS data in a future version.
