### ISSUE TITLE
Classes for evaluation (1 Megapixel dataset)

### ISSUE THREAD

**Issue by alochtuwien** [prophesee-ai/prophesee-automotive-dataset-toolbox#23]
Hi!
Does the [1 Megapixel Automotive Detection Dataset](https://www.prophesee.ai/2020/11/24/automotive-megapixel-event-based-dataset/) use all the classes: {"0": "pedestrian", "1": "two wheeler", "2": "car", "3": "truck", "4": "bus", "5": "traffic sign", "6": "traffic light"}  in the evaluation (Reported 0.43 mAP) or only 3 (Pedestrians, Cars (As a merged truck + bus + car) and Two wheelers)?

**Comment by leonelppsee** [comment]
Hi @alochtuwien,
[1 Megapixel Automotive Detection Dataset](https://www.prophesee.ai/2020/11/24/automotive-megapixel-event-based-dataset/) don't use all the dataset.
 In the paper only pedestrians, two-wheeler and cars are used. Cars means cars only (NOT merged with bus and tracks).

**Comment by lbristiel-psee** [comment]
@alochtuwien for information, we claried the situation on our labels in the README of our repo. See our PR: https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/pull/27/files
