### ISSUE TITLE
Dataset format issues

### ISSUE THREAD

**Issue by shaoyu-liu** [prophesee-ai/prophesee-automotive-dataset-toolbox#33]
This code is used to read files in. dat format, but the format of the dataset I downloaded is. h5. May I ask what operation is required to read the. h5 format dataset through this code, or how to obtain the. dat format from the. h5 format dataset

**Comment by lbristiel-psee** [comment]
Hello,
could you give more information about the dataset you  downloaded?  Which one is it?
The script available in this repo is handling .dat files because the datasets we mention here are made of .dat files.
We also distribute some datasets in pre-processed .h5 format in https://docs.prophesee.ai/stable/datasets.html#precomputed-datasets but those should be used with the SDK that can be installed following those guides https://docs.prophesee.ai/stable/installation/index.html and then check what the ML module can do: https://docs.prophesee.ai/stable/guides/machine_learning.html
Hope this helps,
Laurent for Prophesee Support

**Comment by shaoyu-liu** [comment]
This is the. h5 file I downloaded




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prophesee-ai/prophesee-automotive-dataset-toolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [prophesee-ai/prophesee-automotive-dataset-toolbox] Dataset format issues (Issue #33)





 
Hello,
 could you give more information about the dataset you  downloaded?  Which one is it?
 The script available in this repo is handling .dat files because the datasets we mention here are made of .dat files.
 We also distribute some datasets in pre-processed .h5 format in https://docs.prophesee.ai/stable/datasets.html#precomputed-datasets but those should be used with the SDK that can be installed following those guides https://docs.prophesee.ai/stable/installation/index.html and then check what the ML module can do: https://docs.prophesee.ai/stable/guides/machine_learning.html
 Hope this helps,
 Laurent for Prophesee Support
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

event_representations_ds2_nearest.h5 (228.36M, 2023年11月10日 18:19 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=6e376335d75e8ac20544cf784366021c4f430557075002051a540607544b030707044e575304531e55015053545105035456550d6542305641520d413a145543455210500b1251475e580d463a0243016859065417034347195f563558&t=exs_ftn_download&code=77c5ef03

**Comment by lbristiel-psee** [comment]
This file is not in a format that is supported by our SDK.
- To read [Event HDF5 files](https://docs.prophesee.ai/stable/data/file_formats/hdf5.html), you can use [metavision_viewer](https://docs.prophesee.ai/stable/samples/modules/driver/viewer.html)
- To read [PreProcessed H5 files](https://docs.prophesee.ai/stable/tutorials/ml/data_processing/event_preprocessing.html), you can use [viz_data](https://docs.prophesee.ai/stable/samples/modules/ml/viz_data.html#chapter-samples-ml-viz-data)

But your file does not seem to be in any of those 2 formats.
Can you give more information on how/where you got/built this file?

**Comment by lbristiel-psee** [comment]
For information, we enhanced our documentation on supported HDF5 files in Metavision SDK.
We support 2 formats:
- HDF5 event files: https://docs.prophesee.ai/stable/data/file_formats/hdf5.html
- HEF5 tensor files: https://docs.prophesee.ai/stable/data/file_formats/hdf5_tensor.html

Hope this clarifies
