### ISSUE TITLE
how to change the dat to frame

### ISSUE THREAD

**Issue by xjyisok** [prophesee-ai/prophesee-automotive-dataset-toolbox#34]
dear author
I just download zhe testfileslist02.7z as my dataset.So how can I change the dat files to image frames
Thanks for your answer

**Comment by lbristiel-psee** [comment]
Hello,

those DAT files are not meant to be converted to image frames but are meant to be used as event-based. There is a small tutorial in the repo (https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/blob/master/tutorial.ipynb) that shows how to read event. And in Metavision SDK doc site, there are more explanations on how to use event-based files (like DAT files) in the context of machine learning: https://docs.prophesee.ai/stable/guides/machine_learning.html.

For some information specifically on DAT files, you can also check this page: https://docs.prophesee.ai/stable/data/file_formats/dat.html

Hope this helps,
Laurent for Prophesee Support.
