### ISSUE TITLE
Does the 1 Megapixel Automotive Detection Dataset only contains 7GB data for training?

### ISSUE THREAD

**Issue by XinhaoLuo666** [prophesee-ai/prophesee-automotive-dataset-toolbox#35]
Hello, I'd like to download the 1 Megapixel Automotive Detection Dataset at https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08/files/51. There are only three .7z packages divided into train, val, and test. But the train dataset is only 7 GB and the val dataset is 39GB. Have I downloaded the correct dataset? Or the dataset is intact？Why the val dataset is larger than training dataset?

**Comment by banzhuangonglxh** [comment]
I'd like to download the 1 Megapixel Automotive Detection Dataset at https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08/files/51. There are only three .7z packages divided into train, val, and test. But the train dataset is only 7 GB and the val dataset is 39GB. Have I downloaded the correct dataset? or the dataset is intact？

**Comment by lbristiel-psee** [comment]
Hi,

there is indeed a problem of missing files in the link we currently share.
We are fixing the issue.
In the meantime, please use this link to download the full dataset:
https://dataset.prophesee.ai/index.php/s/8HY0Bv4mOU4RzBm

Sorry for the disturbance,
Laurent for Prophesee Support

**Comment by XinhaoLuo666** [comment]
> Hi,
> 
> there is indeed a problem of missing files in the link we currently share. We are fixing the issue. In the meantime, please use this link to download the full dataset: https://dataset.prophesee.ai/index.php/s/8HY0Bv4mOU4RzBm
> 
> Sorry for the disturbance, Laurent for Prophesee Support

Thank you for your reply!

**Comment by lbristiel-psee** [comment]
For information the datasets hosted behind the link https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08/files/51 now contains all the expected data.
The previous link (https://dataset.prophesee.ai/index.php/s/8HY0Bv4mOU4RzBm) will soon be discontinued.
In case of problem, please create an "issue" in our GitHub repo or [contact Prophesee Support](https://docs.prophesee.ai/stable/faq.html#how-can-i-get-some-help-if-i-was-unable-to-fix-my-problem-using-online-documentation).

**Comment by JDYG** [comment]
Hi, the new shared download link (https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08/files/51) seems has very slow response and download speeds. The download speed is only about 17KB/s and it usually disconnects and fail to download. This means that downloading a 64 GB file would take about 50 days. Has anyone else encountered the same problem?

May I ask if there is any other download link for the Gen4 dataset?

I am located in Singapore and I am very sure my university network is stable and good.

**Comment by lbristiel-psee** [comment]
Hello @JDYG 

the only available download link at the moment is [https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08](https://kdrive.infomaniak.com/app/share/975517/52c7b51a-488e-42d8-a44f-e004f4bd0f08) 

I just tested from Europe (France) and download speed was correct. In the past we had multiple people doing downloads from Asia and it was good enough. Could you try again at a different moment? (maybe try at a quiet moment for Europe, meaning your morning, or maybe during week-end). Could have been a temporary network issue as well.

Hope you can get better download speed soon.
Laurent
