### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by xjyisok** [prophesee-ai/prophesee-automotive-dataset-toolbox#36]
Dear author
      while i use the code below to transfer the dat to image I found something unusual:
      The code is below:
       
![QQ截图20240407154952](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/assets/108609628/a1d2ea7a-ed45-42bb-aa0a-1dbd5f4bcfdc)
       But one error made that x=1308 out of index,however in papers the 1MPX dataset's resolution is 1280x720。is this just an incorrect data produced by camera or the resolution  is not 1280*720

**Comment by lbristiel-psee** [comment]
Hello,
I confirm that the resolution is 1280x720. If you have one event that have x=1308 it can be an error from the sensor iteself or from the decode we used to build the DAT file. If the problem occurs only once you might just want to ignore that event. If the problem occurs multiple times, let us know (with some details about the files affected) and we will investigate.
Best
Laurent for Prophesee Support
