### ISSUE TITLE
How can I download the dataset from a Linux terminal?

### ISSUE THREAD

**Issue by XinhaoLuo666** [prophesee-ai/prophesee-automotive-dataset-toolbox#37]
I'm hoping to download the dataset directly into the server via shell, but it seems like there's some kind of encryption there's in the file. When I use the following command to download "wget --no-check-certificate" https://34-v3-6.download.kdrive.infomaniak.com/2/download/018ebcba-b01b-7b38-a279-b4db28d910b1/sharing", error 410 is reported. Is there any other way I can download the dataset? Thankyou！

**Comment by lbristiel-psee** [comment]
Hello @banzhuangonglxh 
indeed, sorry for the inconvenience.
I assume you are trying to download the dataset "1 Megapixel Automotive Detection"
If so, could you try this direct download link;
[https://kdrive.infomaniak.com/2/app/975517/share/52c7b51a-488e-42d8-a44f-e004f4bd0f08/archive/77d30ba4-5f0f-4834-84f7-65deef75cbae/download](https://kdrive.infomaniak.com/2/app/975517/share/52c7b51a-488e-42d8-a44f-e004f4bd0f08/archive/77d30ba4-5f0f-4834-84f7-65deef75cbae/download)
Hope this helps,
Laurent for Prophesee Support

**Comment by XinhaoLuo666** [comment]
> https://kdrive.infomaniak.com/2/app/975517/share/52c7b51a-488e-42d8-a44f-e004f4bd0f08/archive/77d30ba4-5f0f-4834-84f7-65deef75cbae/download

I'm afraid that I can't download the dataset through this link, it reports an error 409. May be I should use other commands to download the dataset?

Follow is my command and the reported error:

wget --no-check-certificate "https://kdrive.infomaniak.com/2/app/975517/share/52c7b51a-488e-42d8-a44f-e004f4bd0f08/archive/77d30ba4-5f0f-4834-84f7-65deef75cbae/download"

--2024-04-11 15:33:39-- https://kdrive.infomaniak.com/2/app/975517/share/52c7b51a-488e-42d8-a44f-e004f4bd0f08/archive/77d30ba4-5f0f-4834-84f7-65deef75cbae/download
Parsing host kdrive.infomaniak.com (kdrive.infomaniak.com)... 45.157.188.28
Connecting kdrive.infomaniak.com (kdrive.infomaniak.com)|45.157.188.28|:443... Connected.
An HTTP request has been made and is waiting for a response... 302 Found
Location: https://34-v3-6.download.kdrive.infomaniak.com/2/download/018ecc13-9ade-777c-9995-8b0fc22e5df6/sharing_archive [follow to new URL]
-- 2024-04-11 15:33:40-- https://34-v3-6.download.kdrive.infomaniak.com/2/download/018ecc13-9ade-777c-9995-8b0fc22e5df6/sharing_archive
Parsing host 34-v3-6.download.kdrive.infomaniak.com (34-v3-6.download.kdrive.infomaniak.com)... 185.125.25.102, 185.125.25.107, 185.125.25.105, ...
Connecting 34-v3-6.download.kdrive.infomaniak.com (34-v3-6.download.kdrive.infomaniak.com)|185.125.25.102|:443... Connected.
An HTTP request has been made and is waiting for a response... 409 Conflict
2024-04-11 15:33:44 Error 409: Conflict.

**Comment by lbristiel-psee** [comment]
We don't provide a way to download our datasets via command line. 
If users don't find a workaround (by downloading "manually" essentially), please come back to us and we will try to see how to help you.
