### ISSUE TITLE
Label problem

### ISSUE THREAD

**Issue by xjyisok** [prophesee-ai/prophesee-automotive-dataset-toolbox#38]
Dear author:
  While I use the code below to change the labels.npy to labels.txt（for yolo） I found something unusual:
![label](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/assets/108609628/f5c6aaa0-015c-4d28-9618-005e07b5b5c9)
  In some label.txt  xc is bigger than 1 just like this
![QQ截图20240410214143](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/assets/108609628/60093421-9be5-4818-8b29-0535428e4dd6)
  Is the problem of my code or the prime data has problem?
  Thanks for your answer
  Additionally an anomaly like x=1308 is a low-probability event,after add an conditional statement the problem in my earlier issue will be solved

**Comment by lbristiel-psee** [comment]
> Additionally an anomaly like x=1308 is a low-probability event,
> after add an conditional statement the problem in my earlier issue will be solved

Do you mean that the problem you detected comes from this unexpected event? So if you do some conditional statement in your code, the problem is solved, right? So do you have a problem left?

**Comment by xjyisok** [comment]
no thanks for answering



---Original---
From: "Laurent ***@***.***&gt;
Date: Sat, Apr 13, 2024 00:12 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prophesee-ai/prophesee-automotive-dataset-toolbox] Label problem(Issue #38)




  
Additionally an anomaly like x=1308 is a low-probability event,
 after add an conditional statement the problem in my earlier issue will be solved
  
Do you mean that the problem you detected comes from this unexpected event? So if you do some conditional statement in your code, the problem is solved, right? So do you have a problem left?
