### ISSUE TITLE
RGB frames corresponding to the 1 Megapixel Automotive Detection Dataset

### ISSUE THREAD

**Issue by ercanburak** [prophesee-ai/prophesee-automotive-dataset-toolbox#8]
Hello, and thanks for sharing this great work of yours.

Is it also possible for you to share the RGB images corresponding to the 1 Megapixel Automotive Detection Dataset?

Thanks

**Comment by laurentbristiel** [comment]
Hello,
thanks for the feedback.
Sharing the RGB frames is currently not possible because it would mean a large effort on our side to be compliant with the legal rules (plate numbers, faces etc. would have to be blured).
