### ISSUE TITLE
What is the resolution of the N-CARS dataset?

### ISSUE THREAD

**Issue by zhangxiann** [prophesee-ai/prophesee-automotive-dataset-toolbox#9]
What is the resolution of the N-CARS dataset ? I can not find the introduction of resolution in the paper or the document: [https://www.prophesee.ai/2018/03/13/dataset-n-cars/](https://www.prophesee.ai/2018/03/13/dataset-n-cars/)

**Comment by dmigliore** [comment]
Hi zhangxiann, what do you mean by "resolution of the dataset"?
If you mean the camera, it is an ATIS, so QVGA.
You can find a comparison table here https://arxiv.org/pdf/1904.08405

**Comment by nbourdis-psee** [comment]
Hi zhangxiann,

Thanks for your interest in our dataset!

You can find more details on the way we built it in section A of the supplementary material of the original paper: https://openaccess.thecvf.com/content_cvpr_2018/Supplemental/1083-supp.pdf

As Davide mentionned, the sensor used to acquire the original recordings is ATIS "Gen1". If you were asking for the size of the samples in the dataset, as explained in the supplementary material, they vary: _"We also discard bounding-box with dimensions not respecting the following conditions:  width between 30 and 120 pixels; height between 25 and 100 pixels; ratio between width and height between 0.5 and 2."_

Best regards,
Nicolas

**Comment by zhangxiann** [comment]
> Hi zhangxiann,
> 
> Thanks for your interest in our dataset!
> 
> You can find more details on the way we built it in section A of the supplementary material of the original paper: https://openaccess.thecvf.com/content_cvpr_2018/Supplemental/1083-supp.pdf
> 
> As Davide mentionned, the sensor used to acquire the original recordings is ATIS "Gen1". If you were asking for the size of the samples in the dataset, as explained in the supplementary material, they vary: _"We also discard bounding-box with dimensions not respecting the following conditions: width between 30 and 120 pixels; height between 25 and 100 pixels; ratio between width and height between 0.5 and 2."_ The samples in the N-Cars dataset are cropped & recentered extracts of the original ATIS recordings, at the locations of the bounding-boxes around cars.
> 
> Best regards,
> Nicolas

Thanks. So the height and width of each sample are varied in the  N-Cars dataset ?

**Comment by laurentbristiel** [comment]
> Thanks. So the height and width of each sample are varied in the N-Cars dataset ?

exactly, yes.
